remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [lsusb-ui]
description: [List the USB Devices attached to the macbook with their manufacturer and more information.]